issue - 34
HEO-Platform/heo-web pull request #50
Opened 2021-06-25 22:03 UTC by dpolozov

resizing video player using css at specific screen sizes.
added player controls for ability to go full screen.

2021-06-25 23:52 UTC, grishick commented on src/components/CampaignPage.js
> +import screenfull from 'screenfull';
are these two imports being used here?

2021-06-25 23:52 UTC, grishick commented on src/components/CampaignPage.js
> +import { ChevronLeft, Gift, CheckCircle, ExclamationTriangle, HourglassSplit, XCircle, Fullscreen} from 'react-bootstrap-icons';
I don't think Fullscreen icon is being used in the current solution.

2021-06-25 23:52 UTC, grishick requested changes
Looks like you left behind experimental changes

2021-06-26 00:28 UTC, grishick commented on package.json
> +    "screenfull": "^5.1.0",
do we need this?

2021-06-26 00:28 UTC, grishick requested changes
I think you missed one more

2021-06-26 00:38 UTC, dpolozov commented
I thought I did uninstall the screenful. But didn't check if it got
removed. Out of the house right now

On Fri, Jun 25, 2021, 5:28 PM Greg Solovyev ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I think you missed one more
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HEO-Platform/heo-web/pull/50#pullrequestreview-693258800>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC6YRWH5BFOM2XL2HWT64BTTUUNMDANCNFSM47KUGPTQ>
> .
>

2021-06-26 03:05 UTC, grishick approved these changes

2021-06-26 03:05 UTC, merged